### ISSUE TITLE
Topic with upper cases letters fails to deserialize

### ISSUE THREAD

**Issue by lindycoder** [bakdata/faust-large-message-serializer#11]
Hello!

Thank you for sharing this tool!

While experimenting with it using randomly generated topic names i noticed that having a topic with upper cases will cause a mismatch in the storage key.

Seems that when computing the storage path
```
        storage_accumulated_path = [path, topic, prefix, random_id]
        storage_path = "/".join(filter(None, storage_accumulated_path))
```
The topic is taken as is to be part of the key.

When retrieving the object
```
        _, bucket, key = uri_parser.parse_uri()
        blob_data = self._client.get_object(bucket, key)
```
The whole URl is parsed in the `URIParser` to `.lower()` casing

So one object stored in 
```
s3://my-bucket/MyTopic/values/2583c12c-1346-4a2d-a8c6-a0347bfb8229
```
will attempt to be fetched from
```
s3://my-bucket/mytopic/values/2583c12c-1346-4a2d-a8c6-a0347bfb8229
```

**Comment by philipp94831** [comment]
Hi @lindycoder, we released 2.0.1 with a fix for the issue. Thanks for reporting!
